[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o out"]

[start]
cmd = "dotnet out/AI.Portfolio.Assistant.Api.dll"
